### ISSUE TITLE
request to generate a tag

### ISSUE THREAD

**Issue by ClayStan** [youpy/go-riff#1]
Hi,

I plan to package go-wav into Debian, I found this is a dependency of go-wav, would you mind generating a tag?

Thanks

**Comment by youpy** [comment]
tag has been added ([v0.1.0](https://github.com/youpy/go-riff/releases/tag/v0.1.0)).

A new version of `go-wav` using the above version has also been released.
https://github.com/youpy/go-wav/releases/tag/v0.3.1

**Comment by ClayStan** [comment]
Thanks

The package is now in debian

https://tracker.debian.org/pkg/golang-github-youpy-go-riff

**Comment by ClayStan** [comment]
https://tracker.debian.org/pkg/golang-github-youpy-go-wav
